version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - USER_NAME=JOHN_DOE
    ports:
      - "80:8080"
    volumes:
      - ./server
      - node_modules:server/node_modules
    networks:
      - app-network
    command: nodemon server/main.js
