version: '3'

services:
  front:
    build:
      context: ./client
    container_name: front
    restart: unless-stopped
    ports:
      - "4200:4200"

  server:
    build:
      context: ./server
    container_name: server
    restart: unless-stopped
    ports:
      - "3000:3000"
